### ISSUE TITLE
kosmosctl install/join can set specific images (version)

### ISSUE THREAD

**Issue by kuangcheng66** [kosmos-io/kosmos#125]
***Why would you like to propose this issue*
1. During the kosmos deployment test last week, I found that there was a problem with the latest v0.1.7 floter image. The problem can only be solved by specifying the v0.1.1 version of the floter image. In the future, I hope to specify a specific image when deploying kosmos ( Version);
2. In offline deployment, upload the image to a machine that cannot connect to the external network, and then directly specify different versions of the image.

**What would you like to be added**:
for example:
```
./kosmosctl join cluster 
--name=A 
--cluster-kubeconfig=[A-kubeconfig] 
--cni=[cni, e.g "calico"] 
--default-nic=[nic, e.g "eth0"]
--private-image-registry=registry.paas/cmss/kosmos-io
--image-version=0.1.7
```

**Why is this needed**:

**Comment by ONE7live** [comment]
--clusterlink-floater-version change to --version? Because it is a bit complicated to use, I think we can control which images this version is used for in the code，what do you think?

**Comment by kuangcheng66** [comment]
> --clusterlink-floater-version change to --version? Because it is a bit complicated to use, I think we can control which images this version is used for in the code，what do you think?

Yes, we still have to discuss this issue
