### ISSUE TITLE
Add network connectivity visual analysis

### ISSUE THREAD

**Issue by ONE7live** [kosmos-io/kosmos#127]
**What would you like to be added**:
We need a deeper analysis of network problems, not just the results of connectivity verification. I think providing these functions can support targeted analysis of network problems. 
It can display the analysis results of network faults very intuitively, maybe introducing kosmosctl would be a good choice.

**Why is this needed**:
When I finished checking network connectivity, the command like: "kosmosctl dr -r ghcr.io/kosmos-io --src-kubeconfig A-kubeconfig --dst-kubeconfig B-kubeconfig". 
![image](https://github.com/kosmos-io/kosmos/assets/48648537/d12de5c2-f4a4-401f-a989-2f2c1fa964ae)
Some nodes are not connected to the network. At this time, I want to further investigate what caused the network connection failure. For example, a certain configuration error occurred. I found that I did not have a good way to complete it through Kosmos.

**Comment by duanmengkk** [comment]
This should be very useful!
