### ISSUE TITLE
kosmosctl uninstall returned information

### ISSUE THREAD

**Issue by rxy0210** [kosmos-io/kosmos#131]
**What happened**: 
1. when i want to execute "kosmosctl uninstall", it calls me "kosmos-system ns not found".
<img width="1106" alt="image" src="https://github.com/kosmos-io/kosmos/assets/88012965/06765f6b-1771-4910-adf5-e901e57d15d8">

2. “Not Found err” will be returned here as error
<img width="1167" alt="image" src="https://github.com/kosmos-io/kosmos/assets/88012965/ff4f78a5-b98a-4b79-ab69-dee6ec7fcb3e">

**What you expected to happen**:
1. I think this case should not return error
2. ditto

**How to reproduce it (as minimally and precisely as possible)**:
1. Firstly, i delete "kosmos-system" ns. Next i execute "kosmosctl uninstall".
2. ditto

**Anything else we need to know?**:

**Environment**:
- Kosmos version: 0.1.7
- Others:

**Comment by ONE7live** [comment]
Issue 2 seems to have been fixed, please pull the latest @rxy0210

**Comment by ONE7live** [comment]
Issue 1 seems a bit extreme, but it is true that we cannot guarantee that users will operate in the way we expect. 
I think it is reasonable to modify the verification logic. When we execute uninstall now, kosmos-system will be deleted only when all modules are uninstalled, the code screenshot is missing this piece of logic, you can take a look at line 117 of the latest code.

**Comment by rxy0210** [comment]
> Issue 2 seems to have been fixed, please pull the latest @rxy0210

ok

**Comment by rxy0210** [comment]
> Issue 1 seems a bit extreme, but it is true that we cannot guarantee that users will operate in the way we expect. I think it is reasonable to modify the verification logic. When we execute uninstall now, kosmos-system will be deleted only when all modules are uninstalled, the code screenshot is missing this piece of logic, you can take a look at line 117 of the latest code.

My second picture is misplaced and should be in Issue2.
Issue1 : i think if I fail to execute uninstall the first time, but kosmos-system has been deleted. Then the second time I execute uninstall, I report a problem that kosmos didn't find, which prevents uninstall from succeeding

**Comment by rxy0210** [comment]
i will fix it
