### ISSUE TITLE
Add pull request templete 

### ISSUE THREAD

**Issue by wuyingjun-lucky** [kosmos-io/kosmos#14]

**Comment by duanmengkk** [comment]
Are you working on this issue now ? @lvtaococo

**Comment by lvtaococo** [comment]
Yes, I completed the development today. Thank you.

**Comment by duanmengkk** [comment]
day after day and week after week

**Comment by duanmengkk** [comment]
> Yes, I completed the development today. Thank you.

day after day and week after week，when can we close this issue? This PR will only take 10 minutes of your time
