### ISSUE TITLE
什么时候支持TILL或者M-LAG实现？？？

### ISSUE THREAD

**Issue by birdofprey** [kosmos-io/kosmos#664]
之前的计算机应用技术假设的条件是系统肯定会故障，计算机系统自建设完成那一刻起就是走向故障的。由此为出发点，所有的系统故障都必然产生停机时间，也因此出现了各种故障灾备和故障迁移方案，不论运维还是灾备应急，一切围绕减小和缩短停机时间展开。对应用系统造成的影响也会被记成一种必然发生的事件。现在如果我们换一个假定条件：应用系统不应该出现对业务系统造成的停止响应。那么系统硬件的故障就是一种日常事件，硬件的故障隔离将于业务系统是否停止响应完全解偶，业务系统处于降级运行模式过程中业务可靠性得以保证。从这种假设出发，业务系统全链过程中每一层的双活结构就是设计中的充分必要条件。 智慧的背后是前端边缘模块的支撑，是系统间规范化的数据共享模块和接口普遍成熟，是数据流就像人体血液的自然流淌，是网络和业务系统全链过程中每一层的双活结构设计必然作为充分必要条件。 目前IETF应该抓紧定义一套双活结构协议，解决目前VRRP协议1/2资源浪费问题。

**Comment by duanmengkk** [comment]
...
