### ISSUE TITLE
Kosmosctl needs to support join and unjoin cluster to knode-manager

### ISSUE THREAD

**Issue by ONE7live** [kosmos-io/kosmos#70]
**What would you like to be added**:
kosmosctl support join and unjoin cluster to knode-manager, like join cluster to  multi-cluster network module, e.g: 
kosmosctl join -f member-cluster.yaml --master-kubeconfig=[master-kubeconfig] --cluster-kubeconfig=[member-kubeconfig]

The addition of knode may be as follows: 
kosmosctl join -f knode.yaml --master-kubeconfig=[master-kubeconfig]
![image](https://github.com/kosmos-io/kosmos/assets/48648537/011228c1-1d6e-46e6-9294-ad105718b326)

**Why is this needed**:
We need a way for users to easily and quickly add clusters to our multi-cluster management and orchestration module, which will help improve user experience.

**Comment by zhouhaoA1** [comment]
yeah, i think it is a good feature.
